name: Testing

on: [pull_request, push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install Ionic
        run: npm install -g @ionic/cli @angular/cli
      - name: Install app dependencies
        run: npm install
      - name: test ci
        run: npm ci
      - name: test ng
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
